name: CD - Publish to PyPI

on:
  release:
    types: [ published ]

env:
  PYTHON_VERSION: "3.10"

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
        ref: ${{ github.event.release.tag_name }}

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ env.PYTHON_VERSION }}

    - name: Install build dependencies
      run: |
        set -x
        python -m pip install --upgrade pip
        pip install build twine

    - name: Build package
      run: |
        set -x
        python -m build

    - name: Debug Event
      run: |
        set -x
        echo "Event Name: ${{ github.event_name }}"
        echo "Tag Name: ${{ github.event.release.tag_name }}"
        echo "Release URL: ${{ github.event.release.html_url }}"
        echo "Release Body: ${{ github.event.release.body }}"

    - name: Publish to PyPI
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
      run: |
        set -x
        twine upload dist/*